apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: afram-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Merson-Capital/afram-backend-k8s-workflows-and-orchestration.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: afram
  syncPolicy:
    syncOptions:
      - CreateNamespace=true 
    automated:
      prune: true
      selfHeal: true
